### ISSUE TITLE
Add description about websocket in Swagger

### ISSUE THREAD

**Issue by egortaran** [FosterFlow/fosterflow#135]
Time to do: 30 minutes
- How to connect
- How to sent message
- How to recive

**Comment by brnikita** [comment]
(Nikita) I need to know about all possible errors format

**Comment by brnikita** [comment]
Updated the web-sockets branch:
1. The connection is made with the request “ws://localhost:8000/ws/chats/1/”, in headers we specify “access”
2. Sending a message to a websocket has the following fields:
{
     "chat_id": 1,
     "prompt": "Hello",
     "owner_id": 1,
     "method": "request"
}
3. In the response in the websocket we will receive response:
{
     "id": 34,
     "message_text": "Hello",
     "created_at": "2023-08-24 18:12:20.378780+00:00",
     "chat_id": 1,
     "owner_id": 1,
     "method": "response"
}
4. Next comes the first message from the model with fields:
{
     "chat_id": 1,
     "created_at": "2023-08-24 18:12:20.393336+00:00",
     "id": 35,
     "message_chunk": "",
     "owner_id": 100,
     "status": "start"
}
5. Generation arrives with fields:
{
     "id": 35,
     "message_chunk": "!",
     "status": "progress"
}
6. The answer ends:
{
     "id": 35,
     "message_chunk": "",
     "status": "done"
}
