### ISSUE TITLE
Fix response error into token

### ISSUE THREAD

**Issue by egortaran** [FosterFlow/fosterflow#160]
Time to do: 1 hour
Change "detail" to "details" response.

![0bed1b6b8e](https://github.com/soshace/fosterflow/assets/761219/866eade5-57d3-4bf2-8623-80778674cecd)

**Comment by brnikita** [comment]
![9bbb1e9808](https://github.com/soshace/fosterflow/assets/761219/669523ed-4f49-4619-aaf9-e864082d4b24)
