### ISSUE TITLE
Issue with new node modules. Docker build doesn't work

### ISSUE THREAD

**Issue by brnikita** [FosterFlow/fosterflow#199]
1. Build command doesn't work 
2. Some kind of problem with installing node.js modules. When I add new node.js modules , application doesn't see them.

**Comment by brnikita** [comment]
![Image](https://github.com/FosterFlow/fosterflow/assets/761219/7ca8213b-9ed1-48c0-bff0-8bf1fcd94288)

**Comment by egortaran** [comment]
Need accept pull request
