### ISSUE TITLE
API agents shows only users' profiles

### ISSUE THREAD

**Issue by brnikita** [FosterFlow/fosterflow#200]
agents API returns users' profiles, not agents as we developed into schema.  I also didn't get any models. Currently I need to get models, not users 

![Image](https://github.com/FosterFlow/fosterflow/assets/761219/3abc7d70-c129-491a-89bd-92e99e4d202f)
![Image](https://github.com/FosterFlow/fosterflow/assets/761219/411d6f40-8d12-4bb6-ba44-4315819a7f3d)

**Comment by egortaran** [comment]
This works correctly. You should add the changes that were in the commit: 9e43a7f

![image](https://github.com/FosterFlow/fosterflow/assets/64767049/c94da0dc-ff0f-4d63-bed1-fc5d12343b03)
